### ISSUE TITLE
Lost changes - quantity to measure

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds_metrics_extension#5]
@timgdavies somehow the changes introduced in [d6d5811](https://github.com/open-contracting/ocds_metrics_extension/commit/d6d581109f0d7c0bc898137c8c77bcd8341bf380) have been lost in the commits you made last week - but I can't see where. Could you take a quick look when you get chance?

**Comment by timgdavies** [comment]
I've manually pushed a fix - but can you check I've not messed up anything else?

**Comment by jpmckinney** [comment]
The fix was https://github.com/open-contracting/ocds_metrics_extension/commit/abf9085e5de016291a757a5662338afd283f0efb Seems okay?
